{"name": "test_login[datalist1]", "status": "failed", "statusDetails": {"message": "AssertionError: assert '账号或者密码错误' in '<html lang=\"zh-cmn-Hans\" style=\"display: block;\"><head>\\n<script id=\"serviceworker\">\\n!function(){try{\"serviceWorker\"...lad&amp;ad_position=login&amp;rnd=1614239724740\" style=\"position: absolute; left: -100px; top: -100px;\"></body></html>'", "trace": "self = <TestScripts.test_main.Test_main object at 0x000001D078EB0BB0>\ndatalist = {'assert_word': '账号或者密码错误', 'password': '123456', 'rowNum': 3, 'username': 'xiaoxiao'}\n\n    @allure.story('登录')\n    @pytest.mark.parametrize(\"datalist\", login_data())\n    def test_login(self, datalist):#登录测试方法\n        global driver\n        lo=login(driver)\n        actual_value=lo.login(datalist[\"username\"],datalist[\"password\"])\n        expect_value=datalist[\"assert_word\"]\n>       assert expect_value in actual_value\nE       assert '账号或者密码错误' in '<html lang=\"zh-cmn-Hans\" style=\"display: block;\"><head>\\n<script id=\"serviceworker\">\\n!function(){try{\"serviceWorker\"...lad&amp;ad_position=login&amp;rnd=1614239724740\" style=\"position: absolute; left: -100px; top: -100px;\"></body></html>'\n\ntest_main.py:44: AssertionError"}, "parameters": [{"name": "datalist", "value": "{'rowNum': 3, 'username': 'xiaoxiao', 'password': '123456', 'assert_word': '账号或者密码错误'}"}], "start": 1614239728314, "stop": 1614239731584, "uuid": "a38cb0da-f2d6-463b-8a7e-06d04c6d81fd", "historyId": "e21977f136a0f8059e37466ce4639368", "testCaseId": "d3df0c8efa7695a55d4cf5ba1e339fa3", "fullName": "test_main.Test_main#test_login", "labels": [{"name": "story", "value": "登录"}, {"name": "suite", "value": "test_main"}, {"name": "subSuite", "value": "Test_main"}, {"name": "host", "value": "admin-PC"}, {"name": "thread", "value": "8356-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_main"}]}